from pydantic import BaseModel, Field


class ResponseStats(BaseModel):
    """Reponse for the agent."""

    content: str = Field(
        title="Response Content",
        description="The content generated by the agent.",
    )
    prompt_tokens: int = Field(
        title="Prompt Tokens",
        description="Number of tokens used in the prompt.",
    )
    completion_tokens: int = Field(
        title="Completion Tokens",
        description="Number of tokens generated in the completion.",
    )
    total_tokens: int = Field(
        title="Total Tokens",
        description="Total number of tokens used (input + output).",
    )
    tokens_per_second: float = Field(
        title="Tokens Per Second",
        description="The rate of tokens generated per second.",
    )
